# version 1.16.x config
#
# About axes
# Here you can choose the axe to adapt TreeRecovery
# The following are defaults
#
# axesについて
# ここでTreeRecoveryを適応させる斧を選択できます
# 以下はデフォルトです
#
# axes:
#  - WOODEN_AXE
#  - STONE_AXE
#  - IRON_AXE
#  - GOLDEN_AXE
#  - DIAMOND_AXE
#  - NETHERITE_AXE

axes:
  - WOODEN_AXE
  - STONE_AXE
  - IRON_AXE
  - GOLDEN_AXE
  - DIAMOND_AXE
  - NETHERITE_AXE

# About stripped_logs and stripped_woods
# Here you can select the tree to which you want TreeRecovery to apply
# The following are the defaults
#
# stripped_logsとstripped_woodsについて
# ここでTreeRecoveryを適応させる木を選択できます
# 以下はデフォルトです
#
# stripped_logs:
#  - STRIPPED_OAK_LOG
#  - STRIPPED_SPRUCE_LOG
#  - STRIPPED_BIRCH_LOG
#  - STRIPPED_JUNGLE_LOG
#  - STRIPPED_ACACIA_LOG
#  - STRIPPED_DARK_OAK_LOG
#  - STRIPPED_CRIMSON_STEM
#  - STRIPPED_WARPED_STEM
#
# stripped_woods:
#  - STRIPPED_OAK_WOOD
#  - STRIPPED_SPRUCE_WOOD
#  - STRIPPED_BIRCH_WOOD
#  - STRIPPED_JUNGLE_WOOD
#  - STRIPPED_ACACIA_WOOD
#  - STRIPPED_DARK_OAK_WOOD
#  - STRIPPED_CRIMSON_HYPHAE
#  - STRIPPED_WARPED_HYPHAE

stripped_logs:
  - STRIPPED_OAK_LOG
  - STRIPPED_SPRUCE_LOG
  - STRIPPED_BIRCH_LOG
  - STRIPPED_JUNGLE_LOG
  - STRIPPED_ACACIA_LOG
  - STRIPPED_DARK_OAK_LOG
  - STRIPPED_CRIMSON_STEM
  - STRIPPED_WARPED_STEM

stripped_woods:
  - STRIPPED_OAK_WOOD
  - STRIPPED_SPRUCE_WOOD
  - STRIPPED_BIRCH_WOOD
  - STRIPPED_JUNGLE_WOOD
  - STRIPPED_ACACIA_WOOD
  - STRIPPED_DARK_OAK_WOOD
  - STRIPPED_CRIMSON_HYPHAE
  - STRIPPED_WARPED_HYPHAE
